### ISSUE TITLE
Itch handles for submission

### ISSUE THREAD

**Issue by srijan-paul** [cpp-gamedev/tothemoon#3]
Post your itch.io profiles here so we can submit as a team during the submission period.
Mine is :
profile- <https://itch.io/profile/injuly>
page-  <https://injuly.itch.io/> (not required)

**Comment by karnkaul** [comment]
https://itch.io/profile/karnage42

**Comment by flyingsl0ths** [comment]
https://flying5loths.itch.io/

**Comment by NikolaJelic** [comment]
https://mrpancakes.itch.io/
